services:
  gitlab-runner:
    image: gitlab/gitlab-runner:ubuntu-v18.9.0
    container_name: GL-Runner-Jakarta01
    restart: unless-stopped
    privileged: true
    cpus: "3.5"
    mem_limit: "7g"
    mem_reservation: "5g"
    shm_size: "2g"
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/gitlab-runner/cache/composer:/root/.composer/cache
      - /srv/gitlab-runner/cache/npm:/root/.npm
      - /srv/gitlab-runner/cache/yarn:/root/.yarn
      - /srv/gitlab-runner/cache/pnpm:/root/.local/share/pnpm/store
      - /srv/gitlab-runner/cache/go/pkg:/root/go/pkg
      - /srv/gitlab-runner/cache/go/build:/root/.cache/go-build
      - /srv/docker-buildkit-cache:/buildkit-cache
      - /srv/gitlab-runner/cache:/cache
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - gitlab-runner-net

networks:
  gitlab-runner-net:
    driver: bridge
